name: p9 - Secret
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        run: |
          echo "variable : ${{ vars.TEST_VAR }}"
          echo "secret : ${{ vars.TEST_SECRET }}"